src/client/plugins/login/modules/login.js
as per Adam's suggestion in https://atlassian.kbase.us/browse/KBASE-3007
=> Adding link to Narrative video to login screen

src/client/index.html
Just adds the little blob of JS to index.html. It might be worth thinking about making this a module that gets loaded by the router, then trigger another update when the route changes... but we can talk about that later.
=> Added google analytics block to index.html

config/ui/demo/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, docs/prerequisites.md, docs/quick-deploy.md, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleDevViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogRegistration.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js, src/client/modules/plugins/catalog/modules/widgets/kbaseViewSDKRegistrationLog.js, src/client/modules/plugins/narrativemanager/modules/narrativeManager.js, src/client/modules/plugins/narrativestore/modules/widgets/narrativeStoreView.js, src/client/modules/plugins/userprofile/modules/widgets/collaboratorNetwork.js, src/client/modules/plugins/userprofile/modules/widgets/userSearch.js, src/client/modules/plugins/userprofileservice/modules/userProfile.js
Or is that pIRATES?
This fixes a snafu caused by renamed files in kbase-service-clients-js, some of which were case changes, and only partially updated in source references, but passed tests (truthfully we don't have many unit tests) and manual inspection of rendered pages ... on a Mac, with the stock case insensitive HFS+ filesystem.
My pre-PR tests will now include deployment and testing on a pure ubuntu VM (that is, not mounting kbase-ui from the mac fs, which I commonly do for web dev.)
=> Argh, maties, where there be a sea, there be Pirates

config/ui/dev/build.yml, config/ui/prod/build.yml, mutations/build.js, src/client/modules/app/App.js, tools/dev/package.json
Fixed missing provenance link and landing page
improvements to download and copy widgets on landing page
added  job and shock browser to help debugging download
=> Fixes and new dev tools

src/client/modules/plugins/catalog/config.yml, src/client/modules/plugins/catalog/modules/app_card.js, src/client/modules/plugins/catalog/modules/catalog_admin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogBrowser.js, src/client/modules/plugins/catalog/resources/css/catalog_styles.css
Improves some styling, fix some bugs, and adds an admin page for reviewing release requests.
=> Catalog Admin page + minor improvements

src/client/modules/plugins/catalog/modules/app_card.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogRegistration.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js, src/client/modules/plugins/catalog/resources/css/catalog_styles.css
Also fixes a number of other issues that came up, and allows handling of sorting by favorites and organizing methods by your favorites.
=> Adding favorites to the catalog browser

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/plugins/mainwindow/modules/loginWidget.js
and updated deps to  pick up fixes.
=> Fix missing default avatar in login widget

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/main.js, src/client/modules/plugins/mainwindow/modules/bodyWidget.js, src/client/modules/plugins/mainwindow/modules/mainWindow.js
- New downloader widget misbehaved sometimes upon revisiting from the back button
- Duplicate buttons installed when a slow loading landing page was aborted and a fresh one listed
- Moved dataview title from overview widget to main panel
=> Fix downloader, panel mounting, other

src/client/modules/plugins/catalog/modules/app_card.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js
- fixed favorites counts jitter
- bugfix on favorites button which wasn't working properly in Firefox/Safari
- linked app pages to type pages
=> Small improvements to App Catalog

src/search/assets/css/search.css, src/search/js/homology.js, src/search/views/homology/features_header.html, src/search/views/homology/features_rows.html, src/search/views/homology/homology.html
address several input UI related feedbacks
=> Homology Search UI updates

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/narrativestore/modules/widgets/narrativeStoreView.js
Links from the old App man pages now route methods to the new app catalog page.
=> Minor update in links from old method/app man pages

src/search/js/search.js
This duplicates Matt's PR to fix copy features.
=> Copy features from the Rich workspace

src/search/js/homology.js
fixing bug that prevents all the valid queries.
=> bug fix: missing ! operation

src/search/js/homology.js, src/search/views/homology/features_expanded.html, src/search/views/homology/homology.html, src/search/views/homology/homologyResult.html
addressing feedbacks and bug fixes reported from the internal testing.
=> Homology service UI update

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseViewSDKRegistrationLog.js
This PR adds better error handling on app/module pages, and provides slightly more functionality to the admin panel.
=> More Minor Catalog Improvements

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/userprofile.js, src/client/modules/plugins/userprofile/modules/widgets/userProfileBase.js, src/client/modules/plugins/userprofile/modules/widgets/userProfileEditor.js, src/client/modules/plugins/userprofile/resources/UserProfile/templates/view.html
Fixes: 
User profile was broken, this gets it working again. Still need some additional testing and use-case exercises, as well as code cleanup.
Dashboard was shortly out of sync with changes in narrative method store (which was updated to accommodate the dashboard https://github.com/kbase/narrative_method_store/pull/28).
Added error-checking and display to apps listed in the dashboard narrative panels.
=> Fixes for user profile page and dashboard

src/search/js/homology.js
- copy to narrative works on both features and genomes
- UI updates
=> homology service UI update & bug fix

src/search/assets/css/search.css, src/search/views/homology/features_header.html, src/search/views/homology/features_rows.html
fine tune on result grid alignment
=> homology service UI css updates

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/main.js
Update service clients to pick up catalog update
Green not red (success not danger) for CI deploy environment alert
=> Update service clients dep

src/search/js/homology.js
this will override popup message
=> override popup message

src/client/modules/plugins/catalog/modules/app_card.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js
Fixed a couple small bugs, and added a way for admins to modify client groups of Apps.
=> Catalog Updates

src/search/js/homology.js
dropdown value and label does not match.
=> typo correction

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStats.js
Also hides non-functional admin buttons for non-admin users.
=> Minor update for catalog stats

config/builds/appdev.yml, config/deploy/deploy-appdev.cfg
Added config files for appdev environment
=> Appdev config

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/main.js, src/client/modules/app/styles/kb-ui.css, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/login/modules/login.js, src/client/modules/require-config.js
typeview - fix type spec links
dashboard - update method rendering in narrative widgets
ui - minor fixes
=> Fixes and improvements

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/main.js, src/client/modules/plugins/mainwindow/modules/widgets/alert.js
- updated vis widgets from ui-common#hardy (in kbase-ui-plugin-vis-widgets)
- updated modeling widgets from ui-common#develop (in kbase-ui-plugin-dataview)
- updated widget base (kbase-ui-plugin-widget) small fix to base widget
- minor update to the ci/next/appdev alert to show an unique icon per dev env. Please feel free to suggest alternatives. I think it would be useful to have a unique icon per env to create meaning flags where needed.
=> Update modeling widgets and vis widgets

bower.json, config/bowerInstall.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/require-config.js
- replaced uuid library - the previous one contained a hidden dependency which caused an error in the requirejs amd loader, evident in the met
- updated two dataview widgets which used uuid
- added jsonview (#jsonview for raw json view of any #dataview)
=> Replace uuid lib, dataview fixes and enhancements

config/ui/dev/build.yml, config/ui/prod/build.yml
LP updates and thrift update propagation through to kbase-data-api-client-js.
=> bump landing pages to 0.3

src/client/modules/plugins/catalog/config.yml, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js
Fix for catalog status widget config
Other corrections to catalog status widget
=> Fixes for catalog status widget

config/ui/dev/build.yml, config/ui/prod/build.yml
picks up spec viewer angle bracket fix
=> update typeview plugin #1.0.3

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogFunctionViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStats.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js, src/client/modules/plugins/catalog/modules/widgets/kbaseViewSDKRegistrationLog.js
PR to let us see some changes in CI, includes some better display of functions and fixes some bugs in the registration log widget.
=> Catalog updates for function catalog and other bugfixes

.travis.yml
Back to our regularly scheduled program...
=> Fix .travis.yml so that it doesn't cause a merge conflict

src/search/views/login.html
and less jargony. Text revisions suggested by Inna and Nomi after reviewing user feedback.
See https://atlassian.kbase.us/browse/KBASE-4144
=> Made text on Narrative login page more concise

config/ui/dev/build.yml, config/ui/prod/build.yml
I just commented out the references to that module, since it's breaking the build process.
=> Removed kbase-ui-plugin-ontology-widgets from build process

config/ui/dev/build.yml, config/ui/prod/build.yml
update datawidgets to pick up fixes
=> udpate service clients to pick up catalog client updates

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogService.js
Switch from manual refresh of dynamic service logs to a websocket connection to get immediate updates.
=> Another small update for the sdk dynamic service page

bower.json, config/link.sh, config/ui/dev/build.yml, config/ui/prod/build.yml, mutations/build.js, src/client/modules/app/services/type.js
- updated bluebird library brings smarter error handling, as well as bug fixes
- landing page now allows alternative viewers via the "viewer" query param
- (legacy) genome landing page fix
=> Improvements and fixes

config/ui/dev/build.yml, config/ui/prod/build.yml
Brings new downloaders (genome annotation, assembly) and a minor
downloader improvement.
=> Update to latest dataview plugin

config/ui/dev/build.yml, config/ui/dev/settings.yml, config/ui/prod/build.yml
remove data api demo from menu config
=> pick up latest service clients for workspace client update

config/link.sh, config/ui/dev/build.yml, config/ui/dev/settings.yml, config/ui/prod/build.yml, mutations/build.js
note that the clients are hand-modified from the original generated clients which were copied into the repo.
the clients will ultimately be built completely by the SDK, and using a build process that directly builds the clients
=> update to include the sdk clients and test plugin

config/link.sh, config/ui/dev/build.yml, config/ui/prod/build.yml
and also associated demo plugins for dev
minor updates to dev link.sh
=> update to latest dynamic services (data api) clients

config/ui/dev/build.yml, config/ui/prod/build.yml
For new changes in assembly and taxonomy landing pages.
=> Update data landing page dependency

src/client/modules/plugins/narrativemanager/modules/NarrativeManager-welcome-cell-content.txt
and attempts to fix the premature line-breaks. Also replaced "app/method" with "app" in preparation for upcoming retirement of the term "method."
=> Some minor changes in wording

src/client/modules/plugins/userprofile/resources/UserProfile/templates/no_profile.html
This appears if you haven't yet set up even a basic profile.
=> Edits to message about your profile

config/builds/dev.yml, config/deploy/deploy-appdev.cfg, config/deploy/deploy-ci.cfg, config/deploy/deploy-dev.cfg, config/deploy/deploy-local-dev.cfg, config/deploy/deploy-narrative-dev.cfg, config/deploy/deploy-next.cfg, config/deploy/deploy-prod.cfg, config/deploy/templates/service.yml, config/ui/dev/build.yml, config/ui/dev/settings.yml, config/ui/prod/build.yml, config/ui/prod/settings.yml, mutations/build.js
add configuration to pull in the bulk-ui plugin
add bulk ui to the menu
add configuration for ftp-api url and base directory
=> integrate bulk-ui plugin

src/client/modules/plugins/userprofile/resources/UserProfile/templates/stub_profile.html
as per https://atlassian.kbase.us/browse/KBASE-4509
=>  Edits to message about your profile

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogBrowser.js
nomi added category grouping for default view
i added sort by "favorites" (starts, then title) for default view
also some code fixes and standard reformatting
=> App catalog default view: group by category, sort by favorites

config/ui/dev/build.yml, config/ui/prod/build.yml
- public narrative panel now shows all public narratives
- see https://atlassian.kbase.us/browse/KBASE-1872
=> updated dashboard

src/client/modules/plugins/narrativemanager/content/welcome-cell-content.md, src/client/modules/plugins/narrativemanager/modules/narrativeManager.js
- remove conversion of markdown to html
- move all header tags one level up (so that top header is h1)
=> Fix new narrative cell welcome content

src/client/modules/plugins/narrativemanager/content/welcome-cell-content.md
Changed description of how to delete the welcome cell.
=> Minor tweaks to welcome cell wording

config/ui/dev/build.yml, config/ui/prod/build.yml
=> Update to latest dataview (2.0.2) to pick up fixes for genome landing

config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/App.js, src/client/modules/app/services/session.js, src/search/src/kbaseSession.js, src/search/src/kbaseSessionSync.js, src/search/src/widgets/kbaseLoginFuncSite.js
add update to common-js to Bill's PR 217
=> Pr 217 update

src/client/modules/app/App.js, src/client/modules/app/services/session.js, src/search/src/kbaseSession.js, src/search/src/kbaseSessionSync.js, src/search/src/widgets/kbaseLoginFuncSite.js
Just use a single kbase_session cookie from here on.
=> Removes the management of a kbase_narr_session cookie

src/client/modules/plugins/catalog/modules/data/categories.yml
(Switched the order of those two categories)
=> Put communities after expression

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js
I'm not sure the regexp replacement of help@kbase.us is working. See, for example, https://narrative.kbase.us/#narrativestore/app/genome_assembly
=> Tweaked instrucs for reporting error

README.md, config/deploy/deploy-ci.cfg, config/deploy/deploy-dev.cfg, config/deploy/deploy-next.cfg, config/deploy/deploy-prod.cfg, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/index.html, src/client/modules/app/App.js, src/client/modules/app/services/session.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/narrativemanager/content/welcome-cell-content.md, src/client/modules/plugins/narrativemanager/modules/narrativeManager.js, src/search/config.json, src/search/js/search.js, src/search/src/kbaseSession.js, src/search/src/kbaseSessionSync.js, src/search/src/widgets/kbaseLoginFuncSite.js, src/search/views/search/search.html
- A bit messier than usual because there had been direct commits to staging
=> Merge Develop->Staging

config/ui/dev/build.yml, config/ui/prod/build.yml
dashboard 1.2.4 fixes public narratives widget
=> update to include fixed dashboard

config/ui/dev/build.yml, config/ui/prod/build.yml
- brings in improved menu/title
- fixes hanging message listener
- improves build
=> Update to latest bulk-ui plugin

config/ui/dev/build.yml, config/ui/prod/build.yml
=> update to latest dataview

src/search/views/apps/analysis.html
I'm not sure this file is used anymore. I will change in another place as well.
=> "Search methods" -> "Search apps"

bower.json, mutations/build.js, package.json, src/client/modules/plugins/login/modules/login.js
Fixes https://kbase-jira.atlassian.net/browse/PUBLIC-55 in which a user reported that login failure would not generate an error message, but just appear to continue trying to log in.
=> Fixes login failure error

config/builds/dev.yml, config/deploy/deploy-dev.cfg
- need to add a config for local ui, local auth2 development
=> updated configs to work with ci local development

bower.json, config/ui/dev/build.yml, config/ui/dev/settings.yml, config/ui/prod/build.yml, config/ui/prod/settings.yml
=> move auth account link from menu to login widget

bower.json, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/auth2Session.js
- also rename getAccount to getMe to match changes
=> Update auth2 client and deps

bower.json, config/bowerInstall.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/index.html, src/client/modules/app/services/auth2Session.js, src/client/require-config.js
=> updated auth2 api and client

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js
* format existing params as a table
* auto update param view on any change, including dropdown selection
* added ability to delete parameters (with a confirm dialog to prevent silly things)
=> More updates to make the admin secure param setting easier.

.vscode/formatter.json, src/client/modules/plugins/catalog/modules/app_card.js, src/client/modules/plugins/catalog/modules/function_card.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAdmin.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogFunctionBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogFunctionViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogRegistration.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogService.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogStatus.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogTypeBrowser.js, src/client/modules/plugins/mainwindow/modules/menuWidget.js, src/client/modules/plugins/message/modules/panel.js, src/client/modules/plugins/narrativemanager/modules/createNewPanel.js, src/client/modules/plugins/types/modules/xtypeService.js, src/client/modules/plugins/userprofile/modules/widgets/userProfileBase.js, src/client/modules/plugins/userprofile/modules/widgets/userProfileEditor.js
Removed logging lines since they were interfering with my ability to inspect the log for issues.
The vast number of changes just has to do with the automated application of js-beautify, resulting in standardized formatting being applied. Well, it is annoying but it only happens once.
Also, placed the js-beautify config (which is only lightly tweaked from default) into the repo.
=> Fix pr 281

bower.json, config/ui/dev/build.yml, config/ui/prod/build.yml, mutations/build.js, src/client/index.html, src/client/load-narrative.html, src/client/loading.html, src/client/modules/app/services/auth2Session.js, src/client/modules/app/services/route.js, src/client/modules/app/services/userprofile.js
cache-busting for static html pages
auth2 support for profiles
auth2 client fixes
ui modifications to support auth2 profiles
changes to dashboard and user-profile to support this
ui profile service now creates empty profile for existing user signing in with "stub" profile
=> Fixes and auth2 client updates

bower.json, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/userprofile.js, src/client/modules/lib/knockout-plus.js, src/search/js/require-config.js, src/search/src/kbaseAppState.js, src/search/src/kbaseSession.js, src/search/src/kbaseSessionSync.js, src/search/src/widgets/kbaseLoginFuncSite.js, src/search/src/widgets/kbaseLoginWidget.js, src/search/views/homology/homology.html, src/search/views/search/search.html
- fixes to the search auth2 upgrade, should be working now
- auth2 client updates to support profile editing
=> Search fixes, auth2 client update

mutations/build.js, src/client/modules/app/services/userprofile.js
- the new module bundle was being built for dev off of dist
=> Build fix, ui user profile service update

bower.json, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/lib/userProfile.js
Capture recent development esp. user profile editor
implements TASK-472
=> Update to latest auth2 client

bower.json, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/styles/kb-bootstrap.css
- improved signin error messaging
- improved messaging for signup within signin [wip]
also in ui:
- tweak to kbase "lightweight" bootstrap panel style
implements TASK-472
=> updated auth2 client

config/ui/dev/build.yml, config/ui/prod/build.yml
=> Updated auth2 client and dashboard

config/ui/ci/build.yml, config/ui/dev/build.yml, docs/plugin-development-with-auth2.md
- warn of etc/hosts changes overriding ci
- latest demo plugin demonstrating local module usage
assists TASK-643
=> Doc update and latest demo plugin version

bower.json, docs/plugin-development-with-auth2.md
- Add dynamic service to the example nginx proxy config
- Update service client with collaborators method now using narrative service
in support of TASK-696 & TASK-698
=> Doc update, service client collaborators method update

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/route.js, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
=> improve sidebar behavior, updated auth2 client

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
- fixes search issue in "Your Narratives" widget in the dashboard
- but could also lead to other problems.
=> Include fixed getNarratives() method from service client

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/styles/kb-bootstrap.css
- also modest changes to kb-panel-light to behave better
implements TASK-752
=> Updated auth2 client empahasizing Google provider

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/styles/kb-bootstrap.css
- moved global "kb-panel-help" style into main app
implements TASK-751
=> Updated auth2-client for warning message

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> Update to latest auth2 client with ui improvements and fixes

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/plugins/mainwindow/modules/mainWindow.css
=> Update to latest data landing pages

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> update auth2 client to pick up login page max-width

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/fallback.js, src/client/modules/app/main.js, src/client/modules/app/services/route.js, src/client/modules/app/styles/kb-bootstrap.css, src/client/modules/app/styles/kb-ui.css, src/client/modules/plugins/mainwindow/config.yml, src/client/modules/plugins/mainwindow/modules/bodyWidget.js, src/client/modules/plugins/mainwindow/modules/deploymentWidget.js, src/client/modules/plugins/mainwindow/modules/mainWindow.css, src/client/modules/plugins/mainwindow/modules/mainWindow.js, src/client/modules/plugins/mainwindow/modules/notificationWidget.js, src/client/modules/plugins/mainwindow/modules/sidebarNav.css, src/client/modules/plugins/mainwindow/modules/sidebarNav.js, src/client/modules/plugins/mainwindow/modules/widgets/alert.js
- in order to provide full-window-height scrolling areas as needed by the auth2 client, the ui needed to use modern css layout via flexbox.
- this required some adjustments to styles and the dom structure
- also moved the deployment environment alert from a notification to a permanent part of the header
- also pass a new "source" parameter in routing to indicate the reason for a routing requeset, to support showing an authorization-required tab on the sign-in page.
- includes updated plugins and libraries to support this: kbase-ui-widget, auth2 client, dashboard, bulk-ui
implements: TASK-736, TASK-472
=> Refactor ui layout to use flexbox

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/App.js, src/client/modules/app/analytics.js, src/client/modules/app/narrativeLoader.js, src/client/modules/app/services/connection.js, src/client/modules/app/services/data.js, src/client/modules/app/services/service.js, src/client/modules/app/services/type.js, src/client/modules/plugins/about/modules/panel.js, src/client/modules/plugins/mainwindow/modules/deploymentWidget.js, src/client/modules/plugins/mainwindow/modules/loginWidget.js, src/client/modules/plugins/mainwindow/modules/sidebarNav.js, src/client/modules/plugins/welcome/modules/welcomePanelWidget.js
- login handler routes to dashboard itself
- remove logging lines and commented out code
implements TASK-472
=> Default to login path, not dashboard; code cleanup

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> Updated auth2 client and common js

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> Tweaks to the profile display

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/lib/knockout-plus.js, src/client/modules/startup.js
in support of all things auth2 ui but specifically login: TASK-472 and friends
=> auth2 client fixes

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/userprofile.js
=> Updated auth2 to use the new signin buttons for signup too.

config/builds/appdev.yml, config/builds/dev.yml, config/builds/next.yml, config/builds/prod.yml, config/deploy/appdev.yml, config/deploy/next.yml, config/deploy/prod.yml, mutations/build.js, src/client/index.html, src/client/load-narrative.html
- reconciled merge conflicts with staging
- update all deployment configurations to auth2
- minor code fixes
=> Fix develop to staging merge

bower.json, src/client/modules/plugins/about/modules/services.js
Token creation had broken due to an update in the auth2 api which had not been reflected yet in the ui
=> Fixed token creation tools

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/userprofile.js, src/client/modules/lib/userProfile.js
- if profile missing, create one and populate with defaults
- improved avatar behavior 
implements TASK-736 and TASK-472
=> Fixed several profile behaviors

Makefile, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/connection.js, src/client/modules/app/services/notification.js, src/client/modules/plugins/mainwindow/modules/notificationWidget.js
- minor updates to auth2 profileeditor
- improved notifications widget
- build now ensures proper nodejs version (v6)
=> auth2 updates, build fixes, notifications improvement

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/lib/knockout-plus.js
- no longer display error message for required/empty fields
- added other research interest field
=> small update to auth2 client

bower.json, docs/testing.md, package.json, src/client/modules/app/services/notification.js, src/client/modules/app/services/schema.js, src/client/modules/startup.js, wdio.conf.js
- now have local ui testing working for firefox and phantomjs. phantomjs was problematic due to obscure security settings (required for working with a self-signed cert)
- testing revealed an incompatibility with older browsers -- the offending usage of the "URL" api was replaced.
supports, generally, TASK-469
=> Testing improvements, compatibility fix, minor improvements

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, mutations/build.js, tools/reverse-proxy-server/package.json, tools/reverse-proxy-server/server.js
- adjust to linking api changes in auth2
- improvements to linking as well 
in support of TASK-817
=> Updates to linking

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/styles/kb-bootstrap.css, src/client/modules/plugins/mainwindow/modules/notificationWidget.css, src/client/modules/plugins/mainwindow/modules/notificationWidget.js
- notification item close button improved
- several auth2 client  language, layout, and timeout display and auto cancellation improvements.
in support of TASK-469
=> Updates to auth2 client and minor ui improvements

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/plugins/mainwindow/modules/mainWindow.js, src/client/modules/plugins/mainwindow/modules/notificationWidget.css, src/client/modules/plugins/mainwindow/modules/notificationWidget.js
- notifications widget
- policy agreements in the account manager
=> styling improvements

config/deploy/templates/build-info.js.txt, config/ui/prod/build.yml, mutations/build.js, src/client/index.html, src/client/modules/plugins/about/modules/services.js
Fix commit hash in cache-buster
- it disappeared after switching git libraries
=> Fix to builder

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/services/connection.js, src/client/modules/lib/knockout-plus.js, src/client/modules/plugins/mainwindow/modules/notificationWidget.css, src/client/modules/plugins/mainwindow/modules/notificationWidget.js
- supports disconnected->connected via auto dismiss and type change (regression - this had been supported previously)
- the warning notification type had regressed from warning->warn as the type name, this was restored
- tester plugin and auth2 client updated accordingly.
=> Minor updates to notification widget

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, docs/token-export-import.md, src/client/index.html
- loading page white background
- signin button proper spinner icon
- fix signin button issue due to safari caching
=> auth2 client improvements

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, package.json, test/specs/dataviewSpec.js, test/wdio.conf.local.js
auth2 logout improvement - clears temporary cookies set by login and linking
new tests - for landing pages (wip)
=> auth2 logout improvement, new tests

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/lib/knockout-plus.js
- https://github.com/kbase/kbase-ui-plugin-auth2-client/releases/tag/v1.1.10
- improve "dirty" detection for knockout extension
- addresses: KBASE-5295
=> auth2 client profile editor improvements

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> profile editor error message improvement

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, package.json
- narrative link in summary widget
- blastOutput needed dataTables dep
- TASK-852
=> dataview fixes

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> improvements to assembly landing page

bower.json, config/bowerInstall.yml, config/services.yml, config/ui/ci/build.yml, config/ui/ci/menu.yml, config/ui/dev/build.yml, config/ui/dev/menu.yml, docs/auth2/development.md, docs/auth2/installing-auth2.md, docs/auth2/nginx-ci-routing-example.conf, docs/auth2/nginx-local-auth2-example.conf, src/client/modules/lib/knockout-plus.js, src/client/modules/plugins/mainwindow/modules/mainWindow.css, src/client/require-config.js
- the search added in this update is just the raw search tool - by free text, as well as by tag
- it is incomplete, bug ridden, but does work if used correctly
- implements overall text search, per type, per-type per-key searching for string and integer (exact value and min/max range), 
- supports paging
- basic view switching per search hit - compact (results) and "dump" detail views to assist in development and debugging
- custom views enabled and implemented for narrative, but does nothing different at the moment
- this tool will be finished, since it is meant to expose all features of object search
- however, next on the list is type-summary level searching, to allow drill-down
- and a custom detail view for narrative.
=> Changes to support and incorporate RESKE search prototype [TASK-886]

bower.json, config/ui/ci/build.yml, config/ui/ci/menu.yml, config/ui/dev/build.yml, config/ui/dev/menu.yml
- free text search over types, exposed in hamburger menu as RESKE Search
=> Updated RESKE search [TASK-887]

bower.json, config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
- updated reske search plugin
- add search to sidebar nav
=> Updates to support RESKE search [TASK-890]

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/analytics.js, src/client/modules/app/services/analytics.js, src/client/modules/app/services/ko-component.js, src/client/modules/app/styles/kb-icons.css
- updated RESKE search client
- google analytics integration update [wip]
- kbase data icon fix
=> Updates to support RESKE search

bower.json, config/services.yml, config/ui/ci/build.yml, config/ui/ci/menu.yml, config/ui/dev/build.yml, config/ui/dev/menu.yml, docs/auth2/development.md, docs/auth2/nginx-ci-routing-example.conf, src/client/modules/plugins/about/modules/services.js
other minor changes as well, including:
- remove auth1 config
- dev deploy doc and example updates
- dynamic service client (kb_common) improved under cancellation
=> add jgi search plugin to dev and ci builds

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/require-config.js
also minor improvements to RESKE search
=> Updated JGI search

config/ui/ci/build.yml, config/ui/dev/build.yml
- supports and-ing search terms.
=> Updated jgi-search plugin [TASK-921]

config/ui/ci/build.yml, config/ui/dev/build.yml
- brings in genbank file recognition
=> update jgi-search [TASK-921]

docs/plugin-development-with-auth2.md
added install nginx and changed restart to start (after testing installation success)
=> updated docs

config/ui/ci/build.yml, config/ui/dev/build.yml
adds search expression parsing for english-language operators: and, not, or
=> updated jgi search [TASK-921]

config/ui/ci/build.yml, config/ui/dev/build.yml
updated ui to collapse the genome and feature browsers on the left
added paging to the genome and feature browsers
tweaked the widget to layout the  legend better
still a rough prototype / playground
=> Updates to RESKE gene GO comparison prototype [TASK-1025]

config/ui/ci/build.yml, config/ui/dev/build.yml
- adds partial implementation of data cart (cart but no copy)
=> update to reske search [TASK-1051]

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/lib/knockout-plus.js
- also added knockout svg template loader
=> updated reske gene prediction [TASK-1051]

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/lib/knockout-plus.js
- fixed some search prototype regressions
- fixed views for data search
- more progress on data carts for data search (almost have copy)
- search all in data search (use *)
- genomes sort in gene prediction tool
=> RESKE client prototype updates

config/ui/ci/build.yml, config/ui/dev/build.yml
- adds missing css file which was breaking FF
=> updated reske ke prototype [TASK-1025]

mutations/build.js
- also issue warning and skip empty js files
=> improve uglifyjs error handling

config/ui/ci/build.yml, config/ui/dev/build.yml, docs/developing-plugins.md, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
- including tweaked left-nav buttons
- updated plugin dev doc
=> updated reske [TASK-1025, TASK-1051]

config/services.yml, config/ui/ci/build.yml, config/ui/dev/build.yml
- primarily integrating improved data search "browser" interface, with expandable rows, per-type "landing page in a nutshell" viewers
- also data copy works, but is still very much WIP
=> updated reske search [TASK-1051]

config/ui/ci/build.yml, config/ui/dev/build.yml
- minor tweaks to date display
=> updated reske admin [TASK-1022]

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/app/styles/kb-ui.css, src/client/modules/plugins/mainwindow/modules/bodyWidget.js, src/client/modules/plugins/mainwindow/modules/titleWidget.js, src/client/modules/plugins/mainwindow/modules/widgets/error.js
- updates to the functional profile viewer
- minor improvements to title display layout and styles
- minor improvements to error handling (yet another error structure to handle)
=> reske prototype updates

config/ui/ci/build.yml, config/ui/dev/build.yml
- sorts in descending date order now :)
=> updated ke-admin [TASK-1022]

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
- updated feeds prototype plugin
- add visual "new items" indicator to left nav menu item
=> Update to latest feeds prototype [TASK-1090]

config/ui/ci/build.yml, config/ui/dev/build.yml, src/client/modules/lib/knockout-plus.js
- also support for missing data default string for the knockout typed text attribute extension.
=> updates to reske search (ui)  [TASK-1051]

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml, src/client/modules/app/styles/kb-bootstrap.css, src/client/modules/plugins/mainwindow/modules/mainWindow.js, src/client/modules/plugins/mainwindow/modules/sidebarNav.css, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
=> Updates to KE prototype, feeds prototype

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- fix auto-page-sizing
- add pmo project id to project column
=> updates for jgi search [TASK-1183]

Makefile, deployment/dev/tools/run-image.sh, docs/developing-with-docker.md
- rename run-container -> run-image
- add directory mounting for ext libs
- added docker tips to doc
=> improvements to docker workflow [TASK-1190]

Makefile, bower.json, config/app/ci/plugins.yml, config/app/dev/plugins.yml, mutations/build.js
- move makeStyles from jgi-search to kbase-common-js
- add local ci preview to makefile
=> minor refactoring and docker workflow improvements [TASK-1190, TASK-1192]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
signin -> sign in
update jgi-search to match stage_status api change
=> fix typo, updated jgi-search [TASK-921]

config/app/ci/plugins.yml, config/app/dev/menus.yml, config/app/dev/plugins.yml, docs/developing-with-docker.md, package-lock.json, tools/server/package-lock.json, tools/server/package.json
initial prototype of simple search (backup plan) to start fleshing out search features
=> updated reske search prototype, added to menu [TASK-1223]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, docs/developing-with-docker.md, src/client/modules/plugins/mainwindow/modules/logoWidget.js
- lots of little and bigger changes
- added jgi logo
- moved magnifying glass to left
-  added pi filter
- better formatting for search result counts 
- refactor staging monitoring - add error detection, simplify global display, add per-row display
- (difficult to test atm, jgi search is wonky)
- added per-column component (needed to handle per-row copy button with status)
- many small fixes
- removed dead code
- also ... remove hub logo and build flag!
=> jgi search improvements [TASK-1198]

config/app/ci/menus.yml, config/app/ci/plugins.yml, config/app/dev/menus.yml, config/app/dev/plugins.yml, config/services.yml, deployment/dev/tools/run-image.sh, src/client/modules/plugins/mainwindow/modules/sidebarNav.js
- primary purpose was to split the code out of the initial prototype, removed unused views and features, clean up code
- secondarily to align with the current mockup
=> first iteration of reske search mvp [TASK-1210]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, src/client/modules/lib/knockout-plus.js
changes mostly under the hood:
- improved caching
- improved paging
- code cleanup
=> reske simple search update [TASK-1210]

config/app/ci/plugins.yml, config/app/dev/plugins.yml
=> reske search update [TASK-1210]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, src/client/modules/lib/knockout-plus.js
- data search fixed history dropdown feature
- jgi search improved staging, staging monitoring, and incorpoprated serverl features and styles from data search
=> updated search (jgi and data) [TASK-1210, TASK-921]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/services.yml
- note it depends on the new staging service
=> jgi search adds filename collision detection [TASK-1214]

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- reflect unimiportable files in the main results
=> updated jgi-search [TASK-1277]

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- help formatting and test content
- type dropdown fixes
=> data search update [TASK-1265]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, deployment/dev/docker/context/Dockerfile, deployment/dev/tools/build_docker_image.sh, src/client/modules/lib/pluginManager.js
- adds better staging support
- adds search history profile sync
- improves dev build (doens't blow docker image cache)
=> updated jgi and data search [TASK-1277]

README.md, config/app/ci/plugins.yml, config/app/dev/plugins.yml
- ensure loading spinner runs on first search of session
=> updated jgi and data search [SCT-200, SCT-123]

src/client/modules/plugins/catalog/modules/catalog_app_viewer.js, src/client/modules/plugins/catalog/modules/catalog_function_viewer.js, src/client/modules/plugins/catalog/modules/catalog_module_viewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogAppViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogFunctionViewer.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleBrowser.js, src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js
- the format is <name> | <catalog> | KBase where <name> is the name of the thing (app, module, function), <catalog> the name of the catalog (App Catalog, etc.)
- this affects both the display of the page (it is the page title), the tab or window title of the browser, and _should_ affect the title of search engine results, at least for Google and others which show rendered javascript.
=> show app name, module name, function name in the page title [PTV-763]

src/client/modules/plugins/catalog/modules/widgets/kbaseCatalogModuleViewer.js
well, there is a lot of code to clean up; this is the trash I just left behind.
=> remove logging line [PTV763]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, deployment/dev/docker/kb-deployment/conf/deployment_templates/nginx.conf.j2
column sorting
minor ui improvements
job tracking  through jgi gateway [wip]
some regressions due to the changes in job monitoring, need to clean this up
=> updated jgi search [SCT-217]

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- proper clocks added to job table
- table simplification and labeling improvement
=> jgi search improvements [SCT-217]

config/ui/ci/build.yml, config/ui/dev/build.yml, config/ui/prod/build.yml
=> fixed auth2 client fixes token passing bug for appdev [SCT-65]

config/app/ci/plugins.yml, config/app/dev/menus.yml, config/app/dev/plugins.yml, deployment/dev/docker/context/Dockerfile, deployment/dev/tools/run-image.sh
- fix self signed cert CN
- remove example-trr plugin, something awry with it
=> fix dev tool issues, improved modal dialog

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- also improves staging dialog
- also fixes and improves deletion of staging monitoring jobs
=> updated jgi search fixes staging bug [SCT-123]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/services.yml, deployment/dev/docker/kb-deployment/conf/deployment_templates/nginx.conf.j2
eapearson/jgi_gateway_eap, erik's development app repo, being merged back into kbaseapps/jgi_gateway
=> refactor gateway service module from jgi_gateway_eap to jgi_gateway

Makefile, bower.json, config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, deployment/dev/tools/run-image.sh, src/client/modules/lib/knockout-plus.js, src/client/modules/plugins/components/config.yml, src/client/modules/plugins/components/modules/clock.js, src/client/modules/plugins/components/modules/components/dialog.js, src/client/modules/plugins/components/modules/components/elapsedClock.js, src/client/modules/plugins/components/modules/components/error.js, src/client/modules/plugins/components/modules/components/help.js, src/client/modules/plugins/components/modules/components/jsonViewer.css, src/client/modules/plugins/components/modules/components/jsonViewer.js, src/client/modules/plugins/components/modules/components/overlayPanel.js, src/client/modules/plugins/components/modules/components/overlayPanelBootstrappish.js, src/client/modules/plugins/components/modules/components/relativeClock.js, src/client/modules/plugins/components/modules/components/table.js, src/client/modules/plugins/components/modules/nanoBus.js
code reorganization focussed on removing obsolete prototyping code, loading components via modules rather than component name strings, and support code changes in ui to support this.
=> updated jgi-search and reske-simple-search: code reorg

bower.json, config/app/ci/plugins.yml, config/app/dev/plugins.yml
- minor ui updates
- add stop words to jgi-search (in the ui side)
=> updated jgi-search and reske-simple-search [SCT-200, SCT-123]

config/app/dev/menus.yml, config/app/dev/plugins.yml, deployment/conf/prod.ini, deployment/dev/docker/kb-deployment/bin/entrypoint.sh, deployment/dev/docker/kb-deployment/conf/deployment_templates/cors.conf.j2, deployment/dev/docker/kb-deployment/conf/deployment_templates/nginx.conf.j2
- improved CORS support for local development against production
- extracted narrative browser out of old reske search plugin (which had been removed) for dev usage (I still find it useful when working.)
- final merge before Q1S2 work begins
=> dev tools improvements

config/app/ci/menus.yml, config/app/dev/menus.yml, config/app/prod/menus.yml
=> move jgi-search into the main hamburger menu [SCT-123]

src/client/modules/plugins/welcome/modules/deprecatedBulkUi.js
(not sure whether syntax is ok -- may need a \ or something to show that a long line was split. @erik, can you fix as needed?)
=> filled in text explaining about bulk import being deprecated

config/app/prod/menus.yml, config/app/prod/plugins.yml, config/release.yml, docs/dev/getting-started.md, release-notes/RELEASE_NOTES_1.5.2.md, release-notes/index.md
- enable job browser plugin, not in menu
- remove jgi search from menu
- updated docs
=> release 1.5.2

bower.json, config/app/ci/menus.yml, config/app/ci/plugins.yml, config/app/dev/plugins.yml, deployment/ci/docker/kb-deployment/conf/config.json.tmpl, deployment/dev/docker/kb-deployment/conf/config.json.tmpl, deployment/dev/docker/kb-deployment/conf/nginx.conf.tmpl, deployment/dev/tools/run-image.sh, deployment/prod/docker/kb-deployment/conf/config.json.tmpl, deployment/proxier/docker/src/conf/nginx.conf.tmpl, src/client/modules/lib/knockout-plus.js
- search mvp2 (data-search plugin) has been updated to checkpoint progress; still working against mock data to enable fleshing out the refactor. The mock data is generated for me (eapearson) and although basic search operations will work with any user, the permissions filters will be wonky.
- update to developer tools to improve the nginx proxy and the configs. (just affects local development.)
=> search mvp2 progress, developer tools update

config/app/ci/plugins.yml, config/app/dev/plugins.yml
- fix ui alignment issues
- fix reference data display of no search , nothing found
=> data search iteration [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- adds data sources filter (reference / narrative)
=> updated reske simple search [SCT-200]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/client/modules/plugins/about/modules/about.js, test/unit-tests/karma.conf.js
- data search: now uses search api to drive narrative search; currently in progress
- simple search: just small adjustments to keep up with search api changes (no new features)
- job browser: restore the suitcase icon (had reverted to cog)
=> updated plugins: data search, simple search, job browser

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- adds search summary preview on tabs
=> updated data-search [SCT-554]

bower.json, config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, mutations/build.js
- adds support for fbamodel and media
- refactored type support
- use type returned by search service; remove duck-typing code
- per-type icon coloring (thus dataview and common-js tweaks)
=> updated data search and simple search [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/client/modules/app/styles/kb-icons.css, src/client/modules/lib/knockout-plus.js, src/client/modules/plugins/components/modules/components/error.js
- fixed odd kbase icon mis-sizing/alignment on landing pages; removing an old hack in the stylesheet fixed it
- component stylesheets may now be loaded globally and once only
- data search error handling improvements, icon added for narrative.
=> icon fixes and data search updates [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- narrative copy dialog works, er, better, filling in the old and prefilling new narrative name
=> data search update [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- internal changes - cancelation
=> updated data search [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- sort by workspace id works!!
=> updated data api adds support for new sort rules structure [SCT-554]

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- just adjusting the path to jgi/search -> jgi-search, to be more consistent with other plugins
=> jgi-search minor update [SCT-123]

release-notes/index.md
- don't know how those got changed to .html!
=> release notes filenames html->md

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml
- fixed copy/view appearing for narratives
- fixed links not opening in new tab/window
- improved searching/no-search messages
- improved handling of duplicate search triggers (still need to solve, but handled for now)
=> updates to data search [SCT-554]

.gitignore, Gruntfile.js, Makefile, config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, config/bowerInstall.yml, deployment/proxier/docker/src/conf/nginx.conf.tmpl, mutations/build.js, package.json
- a recent (jan 2018) change in uglify-es revealed a latent bug in it's inlining algorithm
- only revealed itself in one case within the provenance widget in the dataview plugin
- reducing inlining to level 1 prevents the problem
- other build improvements whilst debugging this
=> build fix for uglify-es inlining bug

config/app/ci/plugins.yml, config/app/dev/plugins.yml, config/app/prod/plugins.yml, config/npmInstall.yml, package.json, src/client/modules/app/services/ko-component.js, src/client/modules/app/styles/kb-bootstrap.css, src/client/require-config.js, test/unit-tests/setup.js
- improved error display
- username error handling more informative when user enters non-compliant characters
- organization typeahead dropdown works better (it would not close after selection)
=> improved sign up [SCT-630]

config/app/dev/plugins.yml, config/app/prod/plugins.yml, deployment/proxier/tools/run-image.sh, deployment/tools/run-image.sh
- provenance widget now uses dagre library - improved layout
- dev run-image, emit stderr
=> data view update, dev tool improvement

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- first pass at exposing genome features
=> data search update: genome features [SCT-644]

config/app/dev/plugins.yml, config/app/prod/plugins.yml, mutations/build.js
- add link for the feedback button (actually important since it is for gathering early feedback, which started 10 minutes ago...)
- minor fix for landing page new provenance widget
=> tweak jgi-search

bower.json, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/client/modules/app/services/route.js, src/client/modules/app/services/session.js, src/client/modules/lib/knockout-plus.js, src/plugins/mainwindow/modules/bodyWidget.js, src/plugins/mainwindow/modules/widgets/error.js
- add roles support to ui's auth2 session
- add support for restricting plugin path by required roles
- jgi-search improved history, and adds admin panel
=> jgi search improvements and support for such

config/app/dev/plugins.yml, config/app/prod/plugins.yml, docs/testing/integration-testing.md, src/test/integration-tests/specs/runner.js, test/wdio.conf.integration.js
- added numeric comparison
- new tests for data-search
=> updated integration testing [SCT-644]

config/app/dev/plugins.yml, config/app/prod/plugins.yml
also data search adds contig count back
=> dashboard adds integration tests, data search better tests

config/app/dev/plugins.yml, config/app/prod/plugins.yml
auth2-client: improved username signup messaging [SCT-630]
=> typeview: handles module w/o version [SCT-744]

config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/client/modules/app/services/menu.js, src/client/modules/app/services/session.js, src/plugins/about/modules/aboutServices.js, src/plugins/mainwindow/modules/components/sidebarMenu.js, src/plugins/mainwindow/modules/menuWidget.js
catalog: improvements to time calculations
ui menu: disable service status menu for non devs (and add capability to filter menus by roles)
=> catalog update, menu update

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- still more to do, but it works enough for review
=> kbase report viewer for landing page [SCT-871]

config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml, config/app/prod/services.yml, config/services.yml
- also wip inclusion of a dashboard refresh for testing, still on the low-down [SCT-709 and friends]
=> data search genome feature search updates [SCT-916]

bower.json, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/plugins/mainwindow/config.yml, src/plugins/mainwindow/modules/components/systemAlertBanner.js, src/plugins/mainwindow/modules/mainWindow.js, src/plugins/mainwindow/modules/systemAlertBanner.js
adapts to new searchapi functionality to provide set of objects in the results
also updates system alert (wip) to use a dynamic service
=> data-search update [SCT-644]

config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml
ui-service: enable wip admin tool in dev build [SCT-713]
=> dashboard2: minor ui improvements [SCT-709]

mutations/build.js, src/client/googledd93a6c35c235da6.html
- if need to keep, the file needs to be specified in the build config
=> temporary(?) inclusion of google site verification file

Makefile, config/app/ui.yml, config/services.yml, mutations/build.js, src/client/googledd93a6c35c235da6.html, src/client/modules/lib/kbaseServiceManager.js, tools/run-image.sh
- for version check against auth during ui startup
=>  add support for rest core services and timeout [SCT-1075]

config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml, config/app/prod/services.yml, config/deploy/appdev.env, config/deploy/ci.env, config/deploy/dev.env, config/deploy/next.env, config/deploy/prod.env, deployment/ci/docker/kb-deployment/conf/config.json.tmpl, docs/dev/prerequisites.md, src/client/modules/app/App.js, src/client/modules/app/services/coreService.js, src/client/modules/lib/appServiceManager.js, src/client/modules/lib/kbaseServiceManager.js, src/client/modules/lib/pluginManager.js
although I want the service version check and qos to be integrated into the ux, for now it will just log errors, exceptions, warnings to the log. This will still help us ensure that the ui will operate in a given env by running the ui against that env and checking the console manually.
=> auth2 service version per env, service version check to console not throw error [SCT-1075]

config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/plugins/mainwindow/modules/titleWidget.css
- truncate long titles, showing ellipsis if overflows
- landing page overview title
- page title
=> improve overflowing titles [SCT-1038, SCT-1075]

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- jobbrowser requires login to access
- queue time displayed while in queue state
- job log button displayed for running jobs
- these fixes put in place while debugging a related issue which required using these tools.
=> jobbrowser/catalog: fixes

README.md
- i thought that worked in GFM?
=> remove target from README [SCT-1075]

config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/plugins/mainwindow/modules/components/systemAlertBanner.js, src/plugins/mainwindow/modules/components/systemAlertToggle.js, src/plugins/mainwindow/modules/mainWindow.js
alerts display in a more "detached" box
alert header button now shows a red alert icon if any alert is ongoing, and an amber clock otherwise (indicating that the alert is a notification of a future event.)
=> system alerts: improved display [SCT-713]

.dockerignore, .gitignore, Makefile, dev/docker-compose.yml, docs/book/development/getting-started.md, docs/book/getting-started/quick-start.md, tools/docker/build-docker-compose-override.js, tools/proxy/Dockerfile
- needed to adjust gitignore to let through the new dev docker compose file
- the proxy build broke because upstream alpine moved to a new version of openssl
- updated some docs
=> adjustments to dev tools

.travis.yml
- a recent (yesterday) to travis broke the  filter condition
=> travis conditional changes

config/app/dev/plugins.yml, config/app/prod/plugins.yml, docs/book/development/getting-started.md, src/client/modules/app/services/rpc.js, src/client/modules/lib/rpc.js, src/plugins/mainwindow/modules/components/systemAlertBanner.js, src/plugins/mainwindow/modules/components/systemAlertToggle.js, src/plugins/mainwindow/modules/models/systemAlerts.js
ui improvements
add timeout of 2sec for the monitor
=> alert updates [SCT-713]

bower.json, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/plugins/mainwindow/modules/components/systemAlertBanner.js
- handle null dates (which means an alert without a known termination)
=> system alert improvements [SCT-713]

Makefile, bower.json, config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml, config/app/prod/services.yml, config/app/ui.yml, deployment/config/appdev.ini, deployment/config/ci.ini, deployment/config/dev.ini, deployment/config/next.ini, deployment/config/prod.ini, src/client/modules/app/services/rpc.js, src/client/modules/lib/rpc.js, src/plugins/mainwindow/modules/components/sidebarMenu.js, tools/docker/build-docker-compose-override.js
also:
minor improvements to data-search and dashboard2
minor improvements to local dev workflow
=> add public-search plugin [SCT-1235]

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- search summary by type
- fixes
=> public-search: minor improvements [SCT-1235]

config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml
- limit types to supported list (omits narrative)
- improved search summary
=>  public-search improvements

config/app/dev/plugins.yml, config/app/prod/plugins.yml, config/npmInstall.yml, mutations/build.js, package-lock.json, package.json, src/client/require-config.js
- and a new available library - vega
=> add similar genomes widget for dataview

bower.json, config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml, config/app/prod/services.yml, src/client/modules/app/services/instrumentation.js, src/client/modules/lib/appServiceManager.js
also add stub support for instrumentation
=>  updated public search [SCT-1235]

bower.json, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/client/modules/lib/rpc.js
- also minor auth2-client update to depend upon component module not global name
=> user profile update - use more modern component structure

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- no further development, just tidying up
=> projects-mvp1: tweaks

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- user can request to join, can cancel
- owner/admin can approve or deny
- many changes to add member, admin, and request info to existing data structures
at this point still just wiring things up to get the basic flow of things working.
next up is admin->user membership invitations
manage members
promote member->admin, demote admin->member
when those pieces are in, there will be a few rounds of fixing data structures, breaking components into common subcomponents, basic layout, error handling, and ui for individual components.
=> orgs ui: add some support for membership [SCT-1612]

config/app/dev/plugins.yml, config/app/prod/plugins.yml
=> orgs: update to handle invitations [SCT-1612]

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- now uses a searchable selection table, similar to narratives
- only narrative searching is not implemented yet
- also layout cleaned up a bit
=> orgs ui: improved user invitation view [SCT-1612]

src/client/google14aa9427cf5f0d8b.html
=> Create google site verification file

bower.json, package-lock.json, package.json, src/client/modules/app/main.js, src/plugins/mainwindow/modules/components/systemAlertBanner.js, src/plugins/mainwindow/modules/mainWindow.js, src/plugins/narrativemanager/modules/createNewPanel.js, tools/proxy/Dockerfile
- and also modest dependency updates
=> Fix narrativemanager call to create narrative with app cell

bower.json, src/client/modules/app/services/session.js
=> fix post-login redirect routing to use the query params

config/app/dev/plugins.yml, config/app/prod/plugins.yml
=> bump feeds version

bower.json, config/app/dev/plugins.yml, config/app/dev/services.yml, config/app/prod/plugins.yml, config/app/prod/services.yml, src/client/modules/app/runtime.js, src/client/modules/app/services/feeds.js, src/client/modules/app/services/menu.js, src/client/modules/app/services/route.js, src/client/modules/app/services/session.js, src/client/modules/app/services/widget.js, src/client/modules/lib/feeds.js, src/plugins/mainwindow/modules/components/sidebarMenu.js, src/plugins/mainwindow/modules/sidebarNav.js
ui: initial impl for feeds menu badge
- for now this is hard-coded in the ui
- more design (internal) needed to determine ultimate destination
=> orgs ui: updated feeds support

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- interface improvements (modest)
=> orgs ui: utilize latest groups listing changes

config/app/dev/plugins.yml, config/app/prod/plugins.yml
=> orgs ui: top level nav moving to ... top!

bower.json, config/app/dev/plugins.yml, config/app/prod/plugins.yml, src/plugins/mainwindow/modules/components/sidebarMenu.js
=> orgs ui: member search and sort

config/app/dev/plugins.yml, config/app/prod/plugins.yml
- faster, gets rid of spurious "no orgs" message
=> orgs ui: improve orgs browser loader

Dockerfile, tools/proxy/Dockerfile
- does mean that not fully reproducible builds, but alpine doesn't allow that anyway
=> don't be so picky and specific about alpine deps. too brittle.

deployment/config/dev_config.ini, src/client/modules/lib/rpc.js, tools/docker/build-docker-compose-override.js, tools/proxy/contents/conf/nginx.conf.tmpl
- on need to change ui config, all based on overriding dynserv in the proxy
=> improve dev support for usage of local dynamic services

config/app/dev/plugins.yml, config/app/prod/plugins.yml, config/app/prod/services.yml
- remove top level search menu
- allow in prod hamburger menu
=> biochem-search updates

config/app/plugins.yml, config/app/services.yml, mutations/build.js, src/client/modules/app/hub.js, src/client/modules/app/services/session.js, src/client/modules/app/services/widget.js, src/plugins/about/modules/aboutServices.js
also reduce to a single build (not dev and prod any longer)
=> add payoff-refactored jgi-search, code cleanup

.travis.yml, deployment/tools/build-travis.bash, deployment/tools/push2dockerhub-travis.sh, tools/docker/build-travis-fake.bash
=> create feature branch build for travis

Dockerfile, Makefile, config/plugins.yml, mutations/build.js
- build is too slow on travis, travis keeps killing it
- avoiding lock file is one suggested fix
=> yarn keeps timing out, also remove example plugin

.travis.yml
- doesn't really matter, but need to trigger a build anyway
=> update to node 10 for travis

.gitignore, config/plugins.yml
dataview: update link to taxon landing page
=> re landing pages: updated link format

config/plugins.yml, src/plugins/login/modules/signinWidget.js
remove user profile tab from auth2-client account view
add user profile menu item to the signing widget
=> Preparing for next release 

mutations/build.js, src/client/modules/app/hub.js, src/client/modules/app/main.js, src/client/modules/app/narrativeLoader.js, src/plugins/mainwindow/modules/components/hamburgerMenu.js
=> remove empty divider in h-menu when not logged in;

config/plugins.yml, mutations/build.js, mutations/mutant.js, tools/docker/build-docker-compose-override.js
updated plugins which support a js "build" dir with compacted (minified) files.
=> updated dataview and dashboard; remove errant source maps during build

config/plugins.yml, mutations/build.js, mutations/mutant.js
- cwd no longer required
- used if provided
- otherwise dist/plugin , then src/plugin
=> simplify plugin.yml

Gruntfile.js, Makefile, src/test/integration-tests/config.json, src/test/integration-tests/specs/common/login.yaml, src/test/integration-tests/specs/merger.js, src/test/integration-tests/specs/runner.js, src/test/integration-tests/specs/theSpec.js, test/wdio.conf.integration.js
- now supports multiple deploy environments in config
=> integration test improvements

config/plugins.yml, deployment/templates/nginx.conf.tmpl, src/client/modules/app/services/route.js, src/client/modules/lib/router.js, src/plugins/about/modules/aboutServices.js, src/plugins/mainwindow/modules/components/hamburgerMenu.js, src/plugins/mainwindow/modules/components/sidebarMenu.js
This is to allow analytics to determine whether the user signed in via signin or signup.
=> add support for "_track_" url path prefix, auth2-client signin/signup use it

config/plugins.yml
version: 0.3.5 to  version: 0.3.6
=> changed react profile plugin version

config/plugins.yml
react profile view release updated to 0.3.7
=> react profile view release updated to 0.3.7

config/npmInstall.yml, config/plugins.yml, mutations/build.js, package.json
- still a tad more to do for biochem-search, but at least it works now
=> biochem-search: fixed and updated

config/plugins.yml
react profile view release updated to 0.3.8
=> react profile view release updated to 0.3.8

deployment/templates/config.json.tmpl, src/plugins/narrativemanager/config.yml
- it has been too long missing
=> add "New Narrative" to the hamburger menu

deployment/templates/config.json.tmpl
- #dashboard still routed to post-login
=> default route now #login

config/plugins.yml
=> sampleview: implement linked data

config/plugins.yml, src/plugins/mainwindow/modules/pluginSupport/iframer.js, src/plugins/mainwindow/modules/pluginSupport/windowChannel.js
auth2-client: has loading display
=> improve loading display

config/plugins.yml, src/client/modules/lib/widget/mount.js, src/plugins/mainwindow/modules/bodyWidget.js
move widget failsafe removal code to finally block
=> job-browser: style updates

config/plugins.yml, deployment/templates/config.json.tmpl, src/plugins/developer/config.yml, src/plugins/developer/modules/developer.js, src/plugins/developer/modules/reactComponents/Developer.js, src/plugins/developer/test/main.yaml
add stub developer internal plugin
=> job-browser improvements

src/plugins/mainwindow/modules/reactComponents/Title.js
- this will change to only support markdown without or with restricted html.
=> fix regression in title - now accepts html

src/client/modules/app/runtime.js, src/plugins/developer/config.yml, src/plugins/developer/modules/developer.js, src/plugins/developer/modules/reactComponents/ConfigEditor.css, src/plugins/developer/modules/reactComponents/ConfigEditor.js, src/plugins/developer/modules/reactComponents/Developer.css, src/plugins/developer/modules/reactComponents/Developer.js, src/plugins/developer/modules/reactComponents/Main.css, src/plugins/developer/modules/reactComponents/Main.js, src/plugins/developer/modules/reactComponents/Tabs.css, src/plugins/developer/modules/reactComponents/Tabs.js
this is to support fiddling with the dynamic service version support just added
=> developer config editor 

src/client/modules/app/hub.js, src/client/modules/app/styles/kb-ui.css
(really just to trigger a build since at this point some plugins are referened by master branch.)
=> remove a few unused styles

config/plugins.yml, src/plugins/developer/modules/reactComponents/Tabs.js, src/plugins/developer/modules/views/Developer.js, src/test/integration-tests/specs/runner.js, src/test/integration-tests/specs/subtasks/login.yaml, tools/proxy/contents/conf/nginx.conf.tmpl
which broke (known to be so!) when refactoring to (p)react.
=> Fixes for integration tests

NOTES.txt, config/plugins.yml, deployment/templates/config.json.tmpl, src/client/search/index.html
- now we gotta fix all the bugs, y'all
=> searchapi2 powered search moves from hamburger menu to sidebar nav!

.github/workflows/main.yml, config/npmInstall.yml, package-lock.json, package.json, release-notes/RELEASE_NOTES_NEXT.md, src/client/js/require-config.js, src/plugins/about/modules/reactComponents/AboutCoreServices.js, src/plugins/about/modules/reactComponents/AboutDynamicServices.js, src/plugins/about/modules/reactComponents/AboutService/AboutService.js, src/plugins/about/modules/reactComponents/AboutService/AboutServiceMain.js, src/plugins/about/modules/reactComponents/Loading.js, src/plugins/about/modules/reactComponents/Loading.styles.js, src/plugins/about/modules/reactComponents/Tabs.css, src/plugins/about/modules/reactComponents/Tabs.js, src/plugins/about/modules/views/AboutServices.js, src/plugins/about/modules/views/style.css, tools/js/build.js, tools/js/mutant.js
This set of changes adds search2 to the "About Services" view of the about plugin.
The addition required a jsonrpc2.0 generic client, which exists in the TS @kbase/ui-lib library.
With some additional work on that client, it is easier to use in JS.
The @kbase/ui-lib is thus now a dependency of kbase-ui.
This required adding a feature to the build tool to convert CommonJS modules to AMD, for usage in kbase-ui.
=> Add search2 to about services

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md
Mostly just annotations to the data-search plugin, marking usage of innerHTML as safe. Removed old widget library because it is unused.
- https://kbase-jira.atlassian.net/browse/UIP-7
* [-] Tests pass in github actions
=> data-search: xss tweaks [UIP-7]

README.md, config/plugins.yml
Few more tweaks to data-search
https://kbase-jira.atlassian.net/browse/UIP-7
=> data-search: improve highlight scrubbing [UIP-7]

release-notes/RELEASE_NOTES_template.md
Just adds the release notes template file, which was missed from the last PR.
- https://kbase-jira.atlassian.net/browse/UIP-9
* [x ] Tests pass locally
* [x ] Tests pass in github actions
* [x ] Manually verified that changes area available (by spinning up an instance and navigating to _X_ to see _Y_)
* [x ] I have made corresponding changes to the documentation
* [x ] My changes generate no new warnings
=> add release notes template

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md
Address xss issues, primarily through annotations. Removed unused code.
https://kbase-jira.atlassian.net/browse/UIP-10
Testing is incorporated into the 
* x] My changes generate no new warnings
* [x ] New and existing unit tests pass locally with my changes
=> feeds: address xss issues [UIP-10]

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md
Takes care of xss scanning script warnings. No really xss issues, but wrapped calls to innerHTML anyway.
https://kbase-jira.atlassian.net/browse/UIP-12
* - ] Added the Github Issue to the title of the PR e.g. (PTV-XXX adds an awesome feature)
* [-] Tests pass in github actions
=> jgi-search: xss cleanup [UIP-12]

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md, src/client/modules/pluginSupport/IFrameController.js, src/client/modules/reactComponents/Notifications/NotificationsMain.js, src/client/modules/reactComponents/Title.js
The auth2 client was first written over 7 years ago. It has been modified from time to time, but has not been subject to major change.
As part of the Credit Engine project, multiple aspects of the auth2 client need to be updated.
The codebase is plain javascript, based on Bootstrap and Knockoutjs. Knockoutjs was fairly popular back then, React was not really a feasible option (as it required compilation), and preact did not yet exist, or was immature. 
However, at this time knockoutjs is quite obscure and it is a burden to expect any other KBase developer to understand no less master it.
So this effort is dedicated to refactoring the codebase to use preact components rather than knockoutjs.
A few visual changes may made where appropriate, but they are kept to a minimum, and certainly are …
=> refactor auth2-client plugin to preact [CE-19]

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md
Add a new landing page for CDSs, and refactor Feature page to be similar and cross-linked
- [PTV-1817](https://kbase-jira.atlassian.net/browse/PTV-1817)
These changes are covered by newly added integration tests. See https://github.com/kbaseIncubator/kbase-integration-tests.
* [-] Tests pass locally
* [-] Tests pass in github actions
* [-] New and existing unit tests pass locally with my changes
* [-] Bump version in config/release.yml
* [-] Rename …
=> add CDS landing page to dataview [PTV-1817]

config/plugins.yml, release-notes/RELEASE_NOTES_2.7.0.md
This is a relatively big release, as it includes changes over three months. This was not intentional, just due to some overlapping sets of changes.
One set of changes affects several plugins, which was part of the effort to investigate html injection vulnerabilities. The changes consist mostly of annotations when usage is considered safe, but also includes various fixes, such as sanitizing test before injection, or using naturally safe text injection, rather than html.
- CE-19: auth2-client: refactored to preact, few user-visible changes
- UIP-10: feeds plugin: address any potential xss exposures, no user visible changes
- UIP-11: auth plugin: address any potential xss exposures; no user visible changes, but some functionality fixes (not reported)
- UIP-12: jgi-search plugin: addresses …
=> Prepare release 2.7.0

config/plugins.yml, release-notes/RELEASE_NOTES_2.7.0.md
This is a relatively big release, as it includes changes over three months. This was not intentional, just due to some overlapping sets of changes.
One set of changes affects several plugins, which was part of the effort to investigate html injection vulnerabilities. The changes consist mostly of annotations when usage is considered safe, but also includes various fixes, such as sanitizing test before injection, or using naturally safe text injection, rather than html.
- CE-19: auth2-client: refactored to preact, few user-visible changes
- UIP-10: feeds plugin: address any potential xss exposures, no user visible changes
- UIP-11: auth plugin: address any potential xss exposures; no user visible changes, but some functionality fixes (not reported)
- UIP-12: jgi-search plugin: addresses …
=> preparing release 2.7.0; catalog: menu link fix; update release notes [UFI-23, UFI-25]

deployment/config/appdev_config.ini, deployment/config/ci_config.ini, deployment/config/dev_config.ini, deployment/config/next_config.ini, deployment/config/prod_config.ini, release-notes/RELEASE_NOTES_NEXT.md, src/client/index.html, src/client/js/gtagSupport.js
> * Summarize the changes.
Google's Universal Analytics is going away shortly, to be replaced by Google Analytics 4. This PR swaps out the old tags for the new. No other code changes should be necessary to get analytics flow, so there are no code changes here!
> * List any dependencies involved in this change.
None
> * list Jira tickets resolved in this PR
https://kbase-jira.atlassian.net/browse/UIP-30
https://kbase-jira.atlassian.net/browse/UIP-25
>   e.g.  https://kbase-jira.atlassian.net/browse/PTV-XXX
> * list Github issues resolved by this PR
> 
>   e.g. https://github.com/myrepo/issues/xxx
N/A
* [n/a] Added the Github Issue to the title of the PR e.g. (PTV-XXX adds an awesome feature)
* [n/a] I have run run the code …
=> UIP-30 update Google Analytics tags

config/plugins.yml
Minor tweaks to the signup form made while investigating a potential lingering issue with the orgs field
- UFI-60 - signup form tweaks
> This section only relevant if this PR is preparing a release
=> minor tweaks to signup form [UFI-60]

config/plugins.yml, release-notes/RELEASE_NOTES_NEXT.md
Fixes the signup form's cancellation button.
- UFI-64: Fix signup cancellation button
> This section only relevant if this PR is preparing a release
=> auth2-client fixes signup cancellation button [UFI-64]
